const ActionType = {
  CONNECT: 'CONNECT',
  DISCONNECT: 'DISCONNECT',
  HANDLE_CONNECTING: 'HANDLE_CONNECTING',
  HANDLE_CONNECTED: 'HANDLE_CONNECTED',
  HANDLE_DISCONNECTING: 'HANDLE_DISCONNECTING',
  HANDLE_DISCONNECTED: 'HANDLE_DISCONNECTED',
  HANDLE_MESSAGE: 'HANDLE_MESSAGE',
};

export default ActionType;
