const ActionType = {
  STATUS_REQUEST: 'STATUS_REQUEST',
  MACHINE_PENDING: 'MACHINE_PENDING',
  MACHINE_OFFLINE: 'MACHINE_OFFLINE',
  MACHINE_ONLINE: 'MACHINE_ONLINE',
};

export default ActionType;
