const ActionType = {
  CONNECT_REQUEST: 'CONNECT_REQUEST',
  CONNECT_PENDING: 'CONNECT_PENDING',
  CONNECT_SUCCESS: 'CONNECT_SUCCESS',
  DICSONNECT_REQUEST: 'DICSONNECT_REQUEST',
  DISCONNECT_PENDING: 'DISCONNECT_PENDING',
  DISCONNECT_SUCCESS: 'DISCONNECT_SUCCESS',
};

export default ActionType;
